import os
from github import Github

# Replace with your own GitHub access token
ACCESS_TOKEN = "your_access_token"
REPO_NAME = "your_username/repo_name"
LABEL = "copilot:all"

# Authenticate with the GitHub API
g = Github(ACCESS_TOKEN)

# Get the target repository
repo = g.get_repo(REPO_NAME)

# Get all closed pull requests
closed_pull_requests = repo.get_pulls(state="closed")

# Iterate through all closed pull requests
for pr in closed_pull_requests:
    # Get the first comment (the PR description)
    first_comment = pr.body

    # Check if the first comment is None, and set it to an empty string if it is
    if first_comment is None:
        first_comment = ""

    # Check if the PR's first message contains 'copilot:all' or 'Generated by Copilot'
    if 'copilot:all' not in first_comment and 'Generated by Copilot' not in first_comment:
        # Append the label to the first comment
        updated_comment = first_comment + "\n\n" + LABEL

        # Update the pull request with the new comment
        pr.edit(body=updated_comment)

        # Print the edited PR link
        print(f"Updated PR: {pr.html_url}")
    else:
        print(f"The PR {pr.html_url} has already been processed. Skipping.")

print("All closed pull requests have been processed.")
